export default function MainNotebookRing() {
  return (
    <div
      aria-hidden="true"
      className="
        absolute
        bottom-10
        left-1/2
        top-10
        z-30
        hidden
        -translate-x-1/2
        flex-col
        justify-between
        md:flex
      "
    >
      {Array.from({ length: 13 }).map((_, index) => (
        <div
          key={index}
          className="
            relative
            h-[14px]
            w-[46px]
          "
        >
          {/* Soft shadows behind the rounded ends */}
          <span
            className="
              absolute
              left-[-1px]
              top-1/2
              z-0
              h-[12px]
              w-[8px]
              -translate-y-1/2
              rounded-full
              bg-black/70
              blur-[1.5px]
            "
          />
          <span
            className="
              absolute
              right-[-1px]
              top-1/2
              z-0
              h-[12px]
              w-[8px]
              -translate-y-1/2
              rounded-full
              bg-black/70
              blur-[1.5px]
            "
          />

          {/* The ring is one continuous gold bar */}
          <span
            className="
              absolute
              left-0
              right-0
              top-1/2
              z-10
              h-[8px]
              -translate-y-1/2
              rounded-full
              bg-gradient-to-r
              from-[#E4AE27]
              via-[#FFE39A]
              to-[#D9A323]
              shadow-[0_1px_2px_rgba(95,65,17,0.42)]
            "
          />
          <span
            className="
              absolute
              left-[6px]
              right-[6px]
              top-[3px]
              z-20
              h-[2px]
              rounded-full
              bg-white/55
            "
          />
        </div>
      ))}
    </div>
  );
}
